name: pnyws
description: Penny wise
version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  injector: ^1.0.8
  shared_preferences: ^0.5.7+2
  get_version: ^0.2.2
  intl: ^0.16.1
  flutter_scale_aware:
    git: https://github.com/jogboms/flutter_scale_aware.git
  rxdart: ^0.24.1
  uuid: ^2.0.4
  flutter_slidable: ^0.5.4
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  google_sign_in: ^4.5.0
  memoize: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
