name: pnyws
description: Penny wise
version: 0.1.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  injector: ^1.0.8
  shared_preferences: ^0.5.4+3
  get_version: ^0.2.0+1
  intl: ^0.16.0
  flutter_scale_aware:
    git:
      url: https://github.com/jogboms/flutter_scale_aware.git
      ref: scale-y

dev_dependencies:
  flutter_test:
    sdk: flutter
  mfsao: ^0.1.3
  mockito: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
#  fonts:
#    - family: SF Pro Display
#      fonts:
#        - asset: assets/fonts/SF-Pro-Display-Light.otf
#          weight: 300
#        - asset: assets/fonts/SF-Pro-Display-Regular.otf
#          weight: 400
#        - asset: assets/fonts/SF-Pro-Display-Medium.otf
#          weight: 500
#        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
#          weight: 600
#        - asset: assets/fonts/SF-Pro-Display-Bold.otf
#          weight: 800
